[tools]
"github:o2sh/onefetch" = "2.28.1"
eza = "0.23.5"
fastfetch = "2.67.1"
github-cli = "2.98.0"
glab = "1.112.0"
jq = "1.8.2"
usage = "6.5.0"
oh-my-posh = '30.9.0'

[settings]
auto_update = true
auto_update_check_duration = "3d"
minimum_release_age = "1d"
disable_backends = ["asdf"]
trusted_config_paths = ["/code"]
use_versions_host = false
fetch_remote_versions_cache = "1h"
color_theme = "catppuccin"
go.set_gobin = false
go.set_goroot = false
