name: publish image and template

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  changes:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.pull_request.merged == true &&
        github.event.pull_request.user.login == 'renovate[bot]'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      distros: ${{ steps.changes.outputs.distros }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - id: changes
        run: .github/workflows/scripts/detect-changes.sh

  publish:
    needs: changes
    if: needs.changes.outputs.distros != '[]'
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJSON(needs.changes.outputs.distros) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Login to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_USERNAME: ${{ github.actor }}
        run: .github/scripts/login-ghcr.sh

      - name: Build and push ${{ matrix.distro }}
        env:
          MISE_GITHUB_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}
        run: ./build.sh --distro "${{ matrix.distro }}" --push

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Create template ${{ matrix.distro }}
        run: ./create-template.sh --distro "${{ matrix.distro }}"

      - name: Test ${{ matrix.distro }}
        run: ./test.sh --distro "${{ matrix.distro }}"

      - name: Publish template ${{ matrix.distro }}
        run: ./create-template.sh --distro "${{ matrix.distro }}" --push
