name: test

on:
  push:
  workflow_dispatch:
    inputs:
      distro:
        description: Distro to build
        required: true
        type: choice
        default: all
        options:
          - all
          - archlinux
          - debian
          - fedora
          - ubuntu

jobs:
  test:
    env:
      INPUT_DISTRO: ${{ inputs.distro }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2

      - name: changes
        id: changes
        run: bun run detect-changes.ts

      - run: echo "${{ steps.changes.candidate_tag }}"
